--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FRashkar-pm/SellUICobblestoneTest
build-by-default: true
branches:
- main
projects:
  SellUI:
    path: SellUI/
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^1.1.3
    lint:
      phpstan: false
...
